### ISSUE TITLE
Django custom management command completion does not work

### ISSUE THREAD

**Issue by psacawa** [iterative/shtab#48]
To replicate:

```
pip install django shtab
django-admin startproject django_tmp

# add "django_tmp" as to  INSTALLED_APPS
# create a custom mgmt. command "django_tmp/management/commands/cmd.py" which uses shtab

./manage.py cmd -s zsh
Traceback (most recent call last):
  File "/home/psacawa/django_tmp/./manage.py", line 22, in <module>
    main()
  File "/home/psacawa/django_tmp/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/psacawa/.pyenv/versions/lektprojekt/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/psacawa/.pyenv/versions/lektprojekt/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/psacawa/.pyenv/versions/lektprojekt/lib/python3.9/site-packages/django/core/management/base.py", line 348, in run_from_argv
    options = parser.parse_args(argv[2:])
  File "/home/psacawa/.pyenv/versions/lektprojekt/lib/python3.9/site-packages/django/core/management/base.py", line 61, in parse_args
    return super().parse_args(args, namespace)
  File "/home/psacawa/.pyenv/versions/3.9.0/lib/python3.9/argparse.py", line 1818, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/psacawa/.pyenv/versions/3.9.0/lib/python3.9/argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/psacawa/.pyenv/versions/3.9.0/lib/python3.9/argparse.py", line 2060, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/psacawa/.pyenv/versions/3.9.0/lib/python3.9/argparse.py", line 2000, in consume_optional
    take_action(action, args, option_string)
  File "/home/psacawa/.pyenv/versions/3.9.0/lib/python3.9/argparse.py", line 1928, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/psacawa/.pyenv/versions/lektprojekt/lib/python3.9/site-packages/shtab/__init__.py", line 724, in __call__
    print(complete(parent or parser, values, preamble=preamble))
  File "/home/psacawa/.pyenv/versions/lektprojekt/lib/python3.9/site-packages/shtab/__init__.py", line 713, in complete
    return completer(
  File "/home/psacawa/.pyenv/versions/lektprojekt/lib/python3.9/site-packages/shtab/__init__.py", line 665, in complete_zsh
    root_options="\n  ".join(
  File "/home/psacawa/.pyenv/versions/lektprojekt/lib/python3.9/site-packages/shtab/__init__.py", line 666, in <genexpr>
    format_optional(opt)
  File "/home/psacawa/.pyenv/versions/lektprojekt/lib/python3.9/site-packages/shtab/__init__.py", line 549, in format_optional
    else "({})".format(" ".join(opt.choices))
TypeError: sequence item 0: expected str instance, int found
```

I have made a  [repo](https://github.com/psacawa/django_tmp) featuring this bug.

**Comment by casperdcl** [comment]
https://github.com/psacawa/django_tmp doesn't seem to exist.

However could you try #48 (`pip install "git+https://github.com/iterative/shtab@fix-non-str-choices#egg=shtab"`)?

**Comment by psacawa** [comment]
I'm sorry, I had forgotten to push. In any case, I've added that repository. That branch solves the stack trace, with the caveat that the autoload header is 

```
#compdef manage.py cmd
```

which I believe tries to add the completion separately for `manage.py` and `cmd`. The upstream distributed `_django` completion script has the compdef

```
#compdef django-admin.py django-admin manage.py
```

I'm not sure that zsh itself natively supports "plugin" completions for subcommands. `_git` does do this, but I believe it's a programmed behaviour of that completion  script.

**Comment by casperdcl** [comment]
probably missing the `prog` argument of your `argparse.ArgumentParser` object?
